device:
  device: 'qemu'
  cwd: './external'
  qemu_path: 'qemu-system-x86_64'
  qemu_args: '-m 2G -smp 4 -cpu host -enable-kvm -nographic -serial mon:stdio'

cores:
  main_core:
    name: 'main'
    conf_path: './external/nuttx/.config'
    elf_path: './external/nuttx/nuttx'
  core1:
    name: ''
    conf_path: ''
    elf_path: ''
  core2:
    name: ''
    conf_path: ''
    elf_path: ''
  core3:
    name: ''
    conf_path: ''
    elf_path: ''
  core4:
    name: ''
    conf_path: ''
    elf_path: ''
  core5:
    name: ''
    conf_path: ''
    elf_path: ''
