config:
  cwd: './external'
  build_dir: './build'

product:

  name: "ntfc-sim"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      defconfig: 'boards/sim/sim/sim/configs/ntfc'
      flash: ''
