config:
  cwd: './external'
  build_dir: './build'

product:

  name: "ntfc-rv-virt-64"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-riscv64'
      exec_args: '-semihosting -M virt,aclint=on -cpu rv64 -smp 1 -bios none -nographic'
      defconfig: 'boards/risc-v/qemu-rv/rv-virt/configs/ntfc64'
      flash: ''
