config:
  cwd: './external'
  build_dir: './build'

product:

  name: "ntfc-armv7a"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-arm'
      exec_args: '-cpu cortex-a7 -nographic
                 -machine virt,highmem=off,virtualization=off,gic-version=2
                 -chardev stdio,id=con,mux=on -serial chardev:con
                 -mon chardev=con,mode=readline'
      defconfig: 'boards/arm/qemu/qemu-armv7a/configs/ntfc'
      flash: ''
