config:
  cwd: './external'
  build_dir: './build'

product:

  name: "nucleo-h743zi"
  cores:
    core0:
      name: 'cm7'
      device: 'serial'
      exec_path: '/dev/ttyACM0'
      exec_args: '115200,n,8,1'
      defconfig: 'boards/arm/stm32h7/nucleo-h743zi/configs/ntfc'
      flash: 'st-flash write $IMAGE_BIN 0x08000000'
      reboot: 'st-flash reset'
