config:
  cwd: './external'

product:

  name: "product"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-aarch64'
      exec_args: '-cpu cortex-a53 -nographic
                 -machine virt,virtualization=on,gic-version=3
                 -net none -chardev stdio,id=con,mux=on
                 -serial chardev:con -mon chardev=con,mode=readline'
      conf_path: './external/nuttx/.config'
      elf_path: './external/nuttx/nuttx'

    core1:
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core2:
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core3:
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core4:
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core5:
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''
