config:
  cwd: './external'
  build_dir: './build'

product:

  name: "ntfc-armv7r"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-arm'
      exec_args: '-M virt,virtualization=on,highmem=off -semihosting -nographic
                 -cpu cortex-r52 -chardev stdio,id=con,mux=on
                 -serial chardev:con -mon chardev=con,mode=readline'
      defconfig: 'boards/arm/qemu/qemu-armv7r/configs/vtfc'
      flash: ''
