device:
  device: 'qemu'
  cwd: './external'
  exec_path: 'qemu-system-arm'
  exec_args: '-M virt,virtualization=on,highmem=off -semihosting -nographic
             -cpu cortex-r52 -chardev stdio,id=con,mux=on
             -serial chardev:con -mon chardev=con,mode=readline'

cores:
  main_core:
    name: 'main'
    conf_path: './external/nuttx/.config'
    elf_path: './external/nuttx/nuttx'
  core1:
    name: ''
    conf_path: ''
    elf_path: ''
  core2:
    name: ''
    conf_path: ''
    elf_path: ''
  core3:
    name: ''
    conf_path: ''
    elf_path: ''
  core4:
    name: ''
    conf_path: ''
    elf_path: ''
  core5:
    name: ''
    conf_path: ''
    elf_path: ''
