config:
  cwd: './external'
  build_dir: './build'

product:

  name: "ntfc-x86-64"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-x86_64'
      exec_args: '-m 2G -smp 4 -cpu host -enable-kvm -nographic -serial mon:stdio'
      defconfig: 'boards/x86_64/intel64/qemu-intel64/configs/vtfc'
      flash: ''
