config:
  cwd: './external'
  build_dir: './build'

product0:

  name: "product0"
  cores:
    core0:
      name: 'core0'
      device: 'sim'
      exec_path: ''
      exec_args: ''
      defconfig: 'boards/sim/sim/sim/configs/vtfc'
      flash: ''

product1:

  name: "product1"
  cores:
    core0:
      name: 'core0'
      device: 'qemu'
      exec_path: 'qemu-system-x86_64'
      exec_args: '-m 2G -smp 4 -cpu host -enable-kvm -nographic -serial mon:stdio'
      defconfig: 'boards/x86_64/intel64/qemu-intel64/configs/vtfc'
      flash: ''

product2:

  name: "product2"
  cores:
    core0:
      name: 'core0'
      device: 'qemu'
      exec_path: 'qemu-system-arm'
      exec_args: '-cpu cortex-a7 -nographic
                 -machine virt,highmem=off,virtualization=off,gic-version=2
                 -chardev stdio,id=con,mux=on -serial chardev:con
                 -mon chardev=con,mode=readline'
      defconfig: 'boards/arm/qemu/qemu-armv7a/configs/vtfc'
      flash: ''

# product3:

#   name: "product3"
#   cores:
#     core0:
#       name: 'core0'
#       device: 'qemu'
#       exec_path: 'qemu-system-aarch64'
#       exec_args: '-cpu cortex-a53 -nographic
#                  -machine virt,virtualization=on,gic-version=3
#                  -net none -chardev stdio,id=con,mux=on
#                  -serial chardev:con -mon chardev=con,mode=readline'
#       defconfig: 'boards/arm64/qemu/qemu-armv8a/configs/vtfc'
#       flash: ''

# product4:

#   name: "product4"
#   cores:
#     core0:
#       name: 'core0'
#       device: 'qemu'
#       exec_path: 'qemu-system-riscv64'
#       exec_args: '-semihosting -M virt,aclint=on -cpu rv64 -smp 1 -bios none -nographic'
#       defconfig: 'boards/risc-v/qemu-rv/rv-virt/configs/vtfc64'
#       flash: ''


# cortex-r52 not supported in upstream qemu yet, so disable this one
# product5:

#   name: "product5"
#   cores:
#     core0:
#       name: 'core0'
#       device: 'qemu'
#       exec_path: 'qemu-system-arm'
#       exec_args: '-M virt,virtualization=on,highmem=off -semihosting -nographic
#                  -cpu cortex-r52 -chardev stdio,id=con,mux=on
#                  -serial chardev:con -mon chardev=con,mode=readline'
#       defconfig: 'boards/arm/qemu/qemu-armv7r/configs/vtfc'
#       flash: ''

