config:
  cwd: './external'
  build_dir: './build'

product:

  name: "nucleo-h745zi"
  cores:
    core0:
      name: 'cm7'
      device: 'serial'
      exec_path: '/dev/ttyACM0'
      exec_args: '115200,n,8,1'
      defconfig: 'boards/arm/stm32h7/nucleo-h745zi/configs/ntfc-all-cm7'
      flash: 'st-flash write $IMAGE_BIN 0x08000000'
      reboot: 'st-flash reset'

    core1:
      name: 'cm4'
      device: 'tty'
      exec_path: '/dev/ttyACM0'
      exec_args: '115200,n,8,1'
      defconfig: 'boards/arm/stm32h7/nucleo-h745zi/configs/ntfc-all-cm4'
      flash: 'st-flash write $IMAGE_BIN 0x08100000'
      reboot: 'st-flash reset'

