config:
  cwd: './external'
  build_dir: './build'

product0:

  name: "nrf5340-dk"
  cores:
    core0:
      name: 'cpuapp'
      device: 'serial'
      exec_path: '/dev/ttyACM0'
      exec_args: '115200,n,8,1'
      defconfig: 'boards/arm/nrf53/nrf5340-dk/configs/ntfc_cpuapp'
      flash: 'nrfutil device program --core application --firmware $IMAGE_HEX'
      reboot: 'nrfutil device reset --core application'
      prompt: 'nsh-cpuapp>'

    core1:
      name: 'cpunet'
      device: 'serial'
      exec_path: '/dev/ttyACM1'
      exec_args: '115200,n,8,1'

      defconfig: 'boards/arm/nrf53/nrf5340-dk/configs/ntfc_cpunet'
      reboot: 'nrfutil device reset'
      flash: 'nrfutil device program --core network --firmware $IMAGE_HEX'
      reboot: 'nrfutil device reset --core network'
      prompt: 'nsh-cpunet>'
