config:                           # common, global configuration options
  cwd: ''                         # path of work directory. eg: /home/work
  build_dir: ''                   # (optional) path to build directory when NTFC is used for building
  timeout: 120                    # timeout per test case. Defaults to 120
  timeout_session: 2400           # timeout per session. Defaults to 2400
  loops: 1                        # specify the number of times to run each testcase. Defaults to 1

product:                          # many products can be supported in tests (product == product0)

  name: "product"                 # product name
  cores:                          # Cores configuration, for know only core0 is used
    core0:                        # Main core (core 0)
      name: ''                    # Core name
      device: ''                  # Choose a device: sim, qemu
      exec_path: ''               # Path of emulator execution for QEMU targets eg: `qemu-system-x86_64`
                                  # Path of serial port for serial targets, eg: `/dev/ttyACM0`
                                  # Empty for simulator.
      exec_args: ''               # Args for emulator execution for QEMU tragets.
                                  # Serial port configuration for serial targets, eg '9600,n,8,1'
                                  # Empty for simulator.

                                  # NTFC can use pre-build image or build it from defconfig
                                  # the behavior will depend on the parameters specified in config.
      conf_path: ''               # (optional) configuration path for this core firmware
      elf_path: ''                # (optional) NuttX ELF path for this core firmware
      defconfig: ''               # (optional) path to build config if NTFC is used for building
      flash: ''                   # (optional) flash command if NTFC is used for flashing
      reboot: ''                  # (optional) System command to reset DUT, eg 'st-flash reset'
      dcmake:                     # (optional) Defines passed to CMake build
        - ["DEFINE1", "VALUE1"]
        - ["DEFINE2", "VALUE2"]


    core1:                        # (optional) Aux core 1  AMP test cases)
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core2:                        # (optional) Aux core 2
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core3:                        # (optional) Aux core 2
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core4:                        # (optional) Aux core 2
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core5:                        # (optional) Aux core 2
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

product1:                         # (optional) next product configuration
  name: "product1" 
  cores:           
    core0:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core1:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core2:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core3:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core4:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''

    core5:         
      name: ''
      device: ''
      conf_path: ''
      elf_path: ''
